function geticondata(){

  var col = [0, -2, -1, 0, 1, 2];
  var row = [0, -4, -3, -2, -1, 0, 1, 2, 3, 4];

  for(i = 0; i < col.length; i++){
    col[i] = col[i] * 12.7 - 12.5;
  }
  for(i = 0; i < row.length; i++){
    row[i] = row[i] * 7.4 - 7.2;
  }

  var hexlinks = [
    //media
    {xcoord: col[1], ycoord: row[3], color: "#F97D46", icon: "peertube", trget: "https://joinpeertube.org/"},
    {xcoord: col[1], ycoord: row[5], color: "#F7991C", icon: "audible", trget: "https://www.audible.com/"},
    {xcoord: col[1], ycoord: row[7], color: "#1BB76E", icon: "imgur", trget: "https://imgur.com/"},
    {xcoord: col[2], ycoord: row[2], color: "#F64D6A", icon: "instagram", trget: "https://www.instagram.com/"},
    {xcoord: col[2], ycoord: row[4], color: "#3668ff", icon: "pandora", trget: "https://www.pandora.com/"},
    {xcoord: col[2], ycoord: row[6], color: "#96a8c8", icon: "xkcd", trget: "https://www.xkcd.com/"},
    {xcoord: col[2], ycoord: row[8], color: "#18D860", icon: "spotify", trget: "https://www.spotify.com/us/"},
    {xcoord: col[3], ycoord: row[1], color: "#4FBF87", icon: "hulu", trget: "https://www.hulu.com/"},
    {xcoord: col[3], ycoord: row[3], color: "#ff0000", icon: "youtube", trget: "https://www.youtube.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#003078", icon: "pennyarcade", trget: "https://www.penny-arcade.com/comic"},
    {xcoord: col[3], ycoord: row[9], color: "#F5C518", icon: "imdb", trget: "https://www.imdb.com/"},
    {xcoord: col[4], ycoord: row[2], color: "#00E59B", icon: "deviantart", trget: "https://www.deviantart.com/"},
    {xcoord: col[4], ycoord: row[4], color: "#AF1E23", icon: "redlettermedia", trget: "http://redlettermedia.com/"},
    {xcoord: col[4], ycoord: row[6], color: "#132661", icon: "disneyplus", trget: "https://www.disneyplus.com/"},
    {xcoord: col[4], ycoord: row[8], color: "#F8BA00", icon: "comedycentral", trget: "http://www.cc.com/"},
    {xcoord: col[5], ycoord: row[3], color: "#FF5500", icon: "soundcloud", trget: "https://soundcloud.com/"},
    {xcoord: col[5], ycoord: row[5], color: "#e50914", icon: "netflix", trget: "https://www.netflix.com/"},
    {xcoord: col[5], ycoord: row[7], color: "#00C5F7", icon: "dailymotion", trget: "https://www.dailymotion.com/us"},
    //main
    {xcoord: col[1], ycoord: row[3], color: "#000000", icon: "blankhex", trget: ""},
    {xcoord: col[1], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[7], color: "#205060", icon: "maps", trget: "https://www.bing.com/maps/"},
    {xcoord: col[2], ycoord: row[2], color: "#006A8D", icon: "mercy", trget: "https://www.mymercy.net/#/login"},
    {xcoord: col[2], ycoord: row[4], color: "#949699", icon: "wikipedia", trget: "https://en.wikipedia.org/wiki/Wikipedia"},
    {xcoord: col[2], ycoord: row[6], color: "#DE5833", icon: "duckduckgo", trget: "https://duckduckgo.com/"},
    {xcoord: col[2], ycoord: row[8], color: "#6133B4", icon: "habitica", trget: "https://habitica.com/"},
    {xcoord: col[3], ycoord: row[1], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[3], ycoord: row[3], color: "#6001D2", icon: "yahoo", trget: "https://www.yahoo.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#0D9071", icon: "bing", trget: "https://www.bing.com/"},
    {xcoord: col[3], ycoord: row[9], color: "#00D6FF", icon: "playstore", trget: "https://play.google.com/store?hl=en_US"},
    {xcoord: col[4], ycoord: row[2], color: "#A4724D", icon: "piratebay", trget: "https://thepiratebay.org/"},
    {xcoord: col[4], ycoord: row[4], color: "#2C546B", icon: "busey", trget: "https://www.busey.com/"},
    {xcoord: col[4], ycoord: row[6], color: "#981E32", icon: "umsl", trget: "https://www.umsl.edu/"},
    {xcoord: col[4], ycoord: row[8], color: "#CE342A", icon: "gmail", trget: "https://mail.google.com/mail/"},
    {xcoord: col[5], ycoord: row[3], color: "#78B942", icon: "timeanddate", trget: "https://www.timeanddate.com/"},
    {xcoord: col[5], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[5], ycoord: row[7], color: "#000000", icon: "blank", trget: ""},
    //work
    {xcoord: col[1], ycoord: row[3], color: "#007AB6", icon: "platform9", trget: "https://mst.platform9.net/ui/login"},
    {xcoord: col[1], ycoord: row[5], color: "#28B573", icon: "groups", trget: "https://groups.google.com/"},
    {xcoord: col[1], ycoord: row[7], color: "#20A464", icon: "googledrive", trget: "https://www.google.com/drive/"},
    {xcoord: col[2], ycoord: row[2], color: "#F48024", icon: "stackoverflow", trget: "https://stackoverflow.com/"},
    {xcoord: col[2], ycoord: row[4], color: "#333333", icon: "github", trget: "https://github.com/"},
    {xcoord: col[2], ycoord: row[6], color: "#5708B4", icon: "udemy", trget: "https://umsystem.udemy.com/organization/home//"},
    {xcoord: col[2], ycoord: row[8], color: "#007A33", icon: "minerlink", trget: "https://minerlink.mst.edu/home_login"},
    {xcoord: col[3], ycoord: row[1], color: "#90151A", icon: "wolfram", trget: "https://www.wolframalpha.com/"},
    {xcoord: col[3], ycoord: row[3], color: "#4CAF50", icon: "w3schools", trget: "https://www.w3schools.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#24386E", icon: "01as", trget: "https://01as.pythonanywhere.com/"},
    {xcoord: col[3], ycoord: row[9], color: "#333333", icon: "pythonanywhere", trget: "https://www.pythonanywhere.com/"},
    {xcoord: col[4], ycoord: row[2], color: "#0253CB", icon: "jira", trget: "https://jira-srv.mst.edu/browse/ASI-8280"},
    {xcoord: col[4], ycoord: row[4], color: "#5C93CE", icon: "asilinks", trget: "https://itweb.mst.edu/auth-cgi-bin/cgiwrap/mstapplink/index.pl"},
    {xcoord: col[4], ycoord: row[6], color: "#2583FE", icon: "fisheye", trget: "https://crucible.mst.edu/crucible/"},
    {xcoord: col[4], ycoord: row[8], color: "#2583FE", icon: "crucible", trget: "https://crucible.mst.edu/~crstatus"},
    {xcoord: col[5], ycoord: row[3], color: "#0078D4", icon: "onedrive", trget: "https://localhost:8443"},
    {xcoord: col[5], ycoord: row[5], color: "#FFCC00", icon: "gitlab", trget: "https://git.mst.edu/apps-team/"},
    {xcoord: col[5], ycoord: row[7], color: "#78d053", icon: "changemanagement", trget: "https://itweb.mst.edu/~cmweb"},
    //gaming
    {xcoord: col[1], ycoord: row[3], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[7], color: "#0566B0", icon: "blizzard", trget: "https://www.blizzard.com/"},
    {xcoord: col[2], ycoord: row[2], color: "#FF2E00", icon: "gamespot", trget: "https://www.gamespot.com/"},
    {xcoord: col[2], ycoord: row[4], color: "#440044", icon: "discord", trget: "https://discordapp.com/"},
    {xcoord: col[2], ycoord: row[6], color: "#cc00aa", icon: "pcgamingwiki", trget: "https://www.pcgamingwiki.com/wiki/Home"},
    {xcoord: col[2], ycoord: row[8], color: "#323471", icon: "gog", trget: "https://www.gog.com/"},
    {xcoord: col[3], ycoord: row[1], color: "#D51D29", icon: "ign", trget: "https://www.ign.com/"},
    {xcoord: col[3], ycoord: row[3], color: "#333333", icon: "steam", trget: "https://store.steampowered.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#FAA740", icon: "nexus", trget: "https://www.nexusmods.com/"},
    {xcoord: col[3], ycoord: row[9], color: "#313131", icon: "epicgames", trget: "https://www.epicgames.com/site/"},
    {xcoord: col[4], ycoord: row[2], color: "#000099", icon: "escapistmagazine", trget: "https://www.escapistmagazine.com/v2/"},
    {xcoord: col[4], ycoord: row[4], color: "#593E85", icon: "twitch", trget: "https://www.twitch.tv/"},
    {xcoord: col[4], ycoord: row[6], color: "#D70252", icon: "polygon", trget: "https://www.polygon.com/"},
    {xcoord: col[4], ycoord: row[8], color: "#3951C6", icon: "gamefaqs", trget: "https://gamefaqs.gamespot.com/"},
    {xcoord: col[5], ycoord: row[3], color: "#E8C75C", icon: "lol", trget: "https://na.leagueoflegends.com/en/"},
    {xcoord: col[5], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[5], ycoord: row[7], color: "#000000", icon: "blank", trget: ""},
    //social
    {xcoord: col[1], ycoord: row[3], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[7], color: "#4A154B", icon: "slack", trget: "https://slack.com/"},
    {xcoord: col[2], ycoord: row[2], color: "#FF0085", icon: "flickr", trget: "https://www.flickr.com/"},
    {xcoord: col[2], ycoord: row[4], color: "#314358", icon: "tumblr", trget: "https://www.tumblr.com"},
    {xcoord: col[2], ycoord: row[6], color: "#3664A2", icon: "facebook", trget: "https://www.facebook.com/"},
    {xcoord: col[2], ycoord: row[8], color: "#6BD126", icon: "kik", trget: "https://www.kik.com/"},
    {xcoord: col[3], ycoord: row[1], color: "#F1E200", icon: "snapchat", trget: "https://www.snapchat.com/"},
    {xcoord: col[3], ycoord: row[3], color: "#1B95E0", icon: "twitter", trget: "https://twitter.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#0077B5", icon: "linkedin", trget: "https://www.linkedin.com/"},
    {xcoord: col[3], ycoord: row[9], color: "#00B1F0", icon: "skype", trget: "https://www.skype.com/en/"},
    {xcoord: col[4], ycoord: row[2], color: "#FA4876", icon: "foursquare", trget: "https://foursquare.com/"},
    {xcoord: col[4], ycoord: row[4], color: "#FF4500", icon: "reddit", trget: "https://www.reddit.com/"},
    {xcoord: col[4], ycoord: row[6], color: "#CB2027", icon: "pinterest", trget: "https://www.pinterest.com/"},
    {xcoord: col[4], ycoord: row[8], color: "#2AB200", icon: "whatsapp", trget: "https://www.whatsapp.com/"},
    {xcoord: col[5], ycoord: row[3], color: "#0084FF", icon: "messenger", trget: "https://www.messenger.com/?_rdr"},
    {xcoord: col[5], ycoord: row[5], color: "#FFD8B1", icon: "4chan", trget: "https://www.4chan.org/"},
    {xcoord: col[5], ycoord: row[7], color: "#000000", icon: "blank", trget: ""},
    //news
    {xcoord: col[1], ycoord: row[3], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[5], color: "#0DBE98", icon: "huffingtonpost", trget: "https://www.huffingtonpost.com/"},
    {xcoord: col[1], ycoord: row[7], color: "#126FB5", icon: "pbs", trget: "https://www.pbs.org/"},
    {xcoord: col[2], ycoord: row[2], color: "#444444", icon: "bbc", trget: "https://www.bbc.com/"},
    {xcoord: col[2], ycoord: row[4], color: "#EC6E3B", icon: "fivethirtyeight", trget: "https://fivethirtyeight.com/"},
    {xcoord: col[2], ycoord: row[6], color: "#CC0000", icon: "cnn", trget: "https://www.cnn.com/"},
    {xcoord: col[2], ycoord: row[8], color: "#444444", icon: "wired", trget: "https://www.wired.com/"},
    {xcoord: col[3], ycoord: row[1], color: "#FD9A00", icon: "sporcle", trget: "https://www.sporcle.com/"},
    {xcoord: col[3], ycoord: row[3], color: "#444444", icon: "washingtonpost", trget: "https://www.washingtonpost.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#006B3A", icon: "onion", trget: "https://www.theonion.com/"},
    {xcoord: col[3], ycoord: row[9], color: "#666666", icon: "nytimes", trget: "https://www.nytimes.com/"},
    {xcoord: col[4], ycoord: row[2], color: "#CC0000", icon: "espn", trget: "https://www.espn.com/"},
    {xcoord: col[4], ycoord: row[4], color: "#008272", icon: "bing", trget: "https://www.bing.com/"},
    {xcoord: col[4], ycoord: row[6], color: "#FF2222", icon: "coronavirusgraphs", trget: "https://coronavirusgraphs.com/"},
    {xcoord: col[4], ycoord: row[8], color: "#034EA2", icon: "weather", trget: "https://weather.com/"},
    {xcoord: col[5], ycoord: row[3], color: "#ED008C", icon: "verge", trget: "https://www.theverge.com/"},
    {xcoord: col[5], ycoord: row[5], color: "#1C6190", icon: "digg", trget: "https://digg.com/"},
    {xcoord: col[5], ycoord: row[7], color: "#FF5722", icon: "blogger", trget: "https://www.blogger.com/"},
    //commerce
    {xcoord: col[1], ycoord: row[3], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[1], ycoord: row[7], color: "#A75CFF", icon: "jet", trget: "https://jet.com/"},
    {xcoord: col[2], ycoord: row[2], color: "#FF5900", icon: "patreon", trget: "https://www.patreon.com/"},
    {xcoord: col[2], ycoord: row[4], color: "#39538C", icon: "bestbuy", trget: "https://www.bestbuy.com/"},
    {xcoord: col[2], ycoord: row[6], color: "#006CB7", icon: "paypal", trget: "https://www.paypal.com/"},
    {xcoord: col[2], ycoord: row[8], color: "#313131", icon: "epicgames", trget: "https://www.epicgames.com/site/"},
    {xcoord: col[3], ycoord: row[1], color: "#ED002C", icon: "petco", trget: "https://www.petco.com/"},
    {xcoord: col[3], ycoord: row[3], color: "#ff3300", icon: "ebay", trget: "https://www.ebay.com/"},
    {xcoord: col[3], ycoord: row[7], color: "#ff9900", icon: "amazon", trget: "https://www.amazon.com/"},
    {xcoord: col[3], ycoord: row[9], color: "#282828", icon: "microcenter", trget: "https://www.microcenter.com/"},
    {xcoord: col[4], ycoord: row[2], color: "#D56205", icon: "etsy", trget: "https://www.etsy.com/"},
    {xcoord: col[4], ycoord: row[4], color: "#800080", icon: "craigslist", trget: "http://www.craigslist.org/"},
    {xcoord: col[4], ycoord: row[6], color: "#F39834", icon: "newegg", trget: "https://www.newegg.com/"},
    {xcoord: col[4], ycoord: row[8], color: "#333333", icon: "steam", trget: "https://store.steampowered.com/"},
    {xcoord: col[5], ycoord: row[3], color: "#323471", icon: "gog", trget: "https://www.gog.com/"},
    {xcoord: col[5], ycoord: row[5], color: "#000000", icon: "blank", trget: ""},
    {xcoord: col[5], ycoord: row[7], color: "#000000", icon: "blank", trget: ""}
  ];

  return hexlinks;
}
